from __future__ import annotations

from enum import StrEnum


class Stage(StrEnum):
    BOOTSTRAP = "BOOTSTRAP"
    LOAD_POLICY = "LOAD_POLICY"
    START_CLOUD_GI = "START_CLOUD_GI"
    ENTER_QUEUE = "ENTER_QUEUE"
    WAIT_GAME_READY = "WAIT_GAME_READY"
    START_AND_DRIVE_BTGI = "START_AND_DRIVE_BTGI"
    MONITOR_AND_GUARD = "MONITOR_AND_GUARD"
    COLLECT_RESULT = "COLLECT_RESULT"
    NOTIFY_AND_ARCHIVE = "NOTIFY_AND_ARCHIVE"
    FINISH = "FINISH"
    FAILED = "FAILED"
    INTERRUPTED = "INTERRUPTED"
    RISK_STOP = "RISK_STOP"
